repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        description: Detect secrets using gitleaks
        language: system
        entry: gitleaks protect --staged --redact --no-banner
        pass_filenames: false
